/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author usuario
 */
public class FrmMenuRM extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuRM
     */
    public FrmMenuRM() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();
        btn_crearRM = new javax.swing.JButton();
        btn_buscarRM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_regresar.setText("REGRESAR");
        btn_regresar.setBorderPainted(false);
        btn_regresar.setContentAreaFilled(false);
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 270, 70));

        btn_crearRM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_crearRM.setText("        CREAR RECETA");
        btn_crearRM.setBorderPainted(false);
        btn_crearRM.setContentAreaFilled(false);
        btn_crearRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearRMActionPerformed(evt);
            }
        });
        jPanel1.add(btn_crearRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 282, 270, 70));

        btn_buscarRM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_buscarRM.setText("BUSCAR RECETA");
        btn_buscarRM.setBorderPainted(false);
        btn_buscarRM.setContentAreaFilled(false);
        btn_buscarRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarRMActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscarRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 270, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pngMenRecM.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        FrmMenuFarmacia menFar= new FrmMenuFarmacia();
        menFar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscarRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarRMActionPerformed
        FrmBuscarRM menBuscarRM= new FrmBuscarRM ();
        menBuscarRM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_buscarRMActionPerformed

    private void btn_crearRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearRMActionPerformed
        FrmCrearRM crearReceta = new FrmCrearRM(this);
        crearReceta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_crearRMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuRM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_buscarRM;
    public javax.swing.JButton btn_crearRM;
    public javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
