
package interfaces;

import base.MetodosSQL;
import clases.Paciente;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author fredd
 */
public class FrmModificarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form FrmCrearPacientes
     */
    private String cedula = "";
    public FrmModificarPaciente(Paciente pac) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtaltura.setText(pac.altura);
        txtantece.setText(pac.antededentes);
        txtape.setText(pac.apellido);
        txtcedu.setText(pac.cedula);
        txtnaci.setText(pac.fechaNaci.toString());
        txtnom.setText(pac.nombre);
        txtpeso.setText(pac.peso);
        this.cedula = pac.cedula;
        
    }

    public boolean fechValida(String fecha) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        try {
            LocalDate.parse(fecha, formatter);
            return true;
        } catch (DateTimeParseException e) {
            return false;
        }
    }

    public static boolean contieneSoloNumeros(String cadena) {
        return cadena.matches("\\d+");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slipeso = new javax.swing.JSlider();
        txtaltura = new javax.swing.JLabel();
        txtpeso = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtantece = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtcedu = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtnaci = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbsangre = new javax.swing.JComboBox<>();
        cbgene = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        btncrearpaciente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        slialtura = new javax.swing.JSlider();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        slipeso.setMaximum(200);
        slipeso.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slipesoStateChanged(evt);
            }
        });
        getContentPane().add(slipeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 388, -1, -1));

        txtaltura.setForeground(new java.awt.Color(0, 0, 0));
        txtaltura.setText("00");
        getContentPane().add(txtaltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 348, 29, -1));

        txtpeso.setForeground(new java.awt.Color(0, 0, 0));
        txtpeso.setText("00");
        getContentPane().add(txtpeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 389, 29, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Antecedentes:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(541, 177, -1, -1));

        txtantece.setColumns(20);
        txtantece.setLineWrap(true);
        txtantece.setRows(5);
        txtantece.setText("//Antecedentes anteriores del\n paciente o cualquier informacion relacionada a ello");
        txtantece.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtantece);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 214, 196, 153));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Tipo de Sangre:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 247, -1, 30));
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 100, 160, -1));
        getContentPane().add(txtcedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 173, 160, -1));
        getContentPane().add(txtape, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 132, 160, -1));
        getContentPane().add(txtnaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 211, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Genero:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 301, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 29, 139, 142));

        cbsangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "O+", "O-", "B+", "B-", "AB+", "AB-" }));
        getContentPane().add(cbsangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 254, 160, -1));

        cbgene.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        getContentPane().add(cbgene, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 301, 167, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Altura:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 341, -1, -1));

        btncrearpaciente.setBackground(new java.awt.Color(255, 255, 51));
        btncrearpaciente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btncrearpaciente.setForeground(new java.awt.Color(0, 0, 0));
        btncrearpaciente.setText("Modificar Paciente");
        btncrearpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncrearpacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btncrearpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 379, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modificar Paciente");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 26, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellidos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 128, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 207, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nombres:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 96, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Identificacion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 169, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Peso:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 382, -1, -1));

        slialtura.setMajorTickSpacing(200);
        slialtura.setMaximum(200);
        slialtura.setMinorTickSpacing(20);
        slialtura.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slialturaStateChanged(evt);
            }
        });
        getContentPane().add(slialtura, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 347, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("yyyy-MM-dd");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 214, 77, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/dafualtt.png"))); // NOI18N
        jLabel15.setText("jLabel5");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 440));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slipesoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slipesoStateChanged
        txtpeso.setText(String.valueOf(slipeso.getValue()));
    }//GEN-LAST:event_slipesoStateChanged

    private void btncrearpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncrearpacienteActionPerformed
        
        if (this.fechValida(txtnaci.getText())) {
           

                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                Paciente pac = new Paciente(txtnom.getText(), txtape.getText(), cedula , LocalDate.parse(txtnaci.getText(), formatter),
                       (String) cbsangre.getSelectedItem(), (String) cbgene.getSelectedItem(), txtaltura.getText(), txtpeso.getText(), txtantece.getText());
                //Insertar un paciente
                if (new MetodosSQL().modificarPaciente(pac)) {
                   
                    JOptionPane.showMessageDialog(null, "Paciente modificado con exito");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Verifique los datos y vuelva a intentarlo");
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese una fecha de nacimiento valida de acuerdo al formato");
            }
        
    }//GEN-LAST:event_btncrearpacienteActionPerformed

    private void slialturaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slialturaStateChanged
        txtaltura.setText(String.valueOf(slialtura.getValue()));
    }//GEN-LAST:event_slialturaStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmModificarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmModificarPaciente(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncrearpaciente;
    private javax.swing.JComboBox<String> cbgene;
    private javax.swing.JComboBox<String> cbsangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider slialtura;
    private javax.swing.JSlider slipeso;
    private javax.swing.JLabel txtaltura;
    private javax.swing.JTextArea txtantece;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtcedu;
    private javax.swing.JTextField txtnaci;
    private javax.swing.JTextField txtnom;
    private javax.swing.JLabel txtpeso;
    // End of variables declaration//GEN-END:variables
}
