/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.Usuario;

/**
 *
 * @author usuario
 */
public class FrmMenuFarmacia extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuRM
     */
    private Usuario usuario;
    public FrmMenuFarmacia(Usuario usuario) {
        
        initComponents();
        this.usuario=usuario;
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    public FrmMenuFarmacia() {
        
        initComponents();
        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_regresarMPrin = new javax.swing.JButton();
        btn_medic = new javax.swing.JButton();
        btn_recetaM = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresarMPrin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_regresarMPrin.setText("REGRESAR");
        btn_regresarMPrin.setBorderPainted(false);
        btn_regresarMPrin.setContentAreaFilled(false);
        btn_regresarMPrin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarMPrinActionPerformed(evt);
            }
        });
        jPanel1.add(btn_regresarMPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 270, 70));

        btn_medic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_medic.setText("       MEDICAMENTO");
        btn_medic.setBorderPainted(false);
        btn_medic.setContentAreaFilled(false);
        btn_medic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_medicActionPerformed(evt);
            }
        });
        jPanel1.add(btn_medic, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 282, 270, 70));

        btn_recetaM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_recetaM.setText("RECETA MÉDICA");
        btn_recetaM.setBorderPainted(false);
        btn_recetaM.setContentAreaFilled(false);
        btn_recetaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recetaMActionPerformed(evt);
            }
        });
        jPanel1.add(btn_recetaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 270, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/pngMenFar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarMPrinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarMPrinActionPerformed
        FrmMenP menP= new FrmMenP(this.usuario);
        menP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarMPrinActionPerformed

    private void btn_recetaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recetaMActionPerformed
        FrmMenuRM menRM= new FrmMenuRM();
        menRM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_recetaMActionPerformed

    private void btn_medicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_medicActionPerformed
        FrmMenuMedicamento menumedic= new FrmMenuMedicamento();
        menumedic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_medicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuFarmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_medic;
    public javax.swing.JButton btn_recetaM;
    public javax.swing.JButton btn_regresarMPrin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
