/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmPreguntasSeguridad extends javax.swing.JFrame {

    /*
    Preguntas de seguridad:
    1. Primera mascota
    2. En que ciudad se conocieron tus padres
    3. Nombre de la primera escuela a la que asististe
    4. Nombre de tu primera mascota
     */
    private ArrayList<String> listaPreguntas;
    private final String pregunta1 = "¿Cuál es el nombre de tu primera mascota?";
    private final String pregunta2 = "¿Cuál es el nombre de la ciudad en la que naciste?";
    private final String pregunta3 = "¿Cuál es el nombre de la primera escuela a la que asististe?";
    private final String pregunta4 = "¿Cuál era el apodo de tu infancia?";
    public Usuario usuario;

    /**
     * Creates new form FrmRecuperarC
     */
    public FrmPreguntasSeguridad() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.generarArray();
        this.cargarPreguntas();
    }

    private void generarArray() {
        this.listaPreguntas = new ArrayList<>();
        this.listaPreguntas.add(pregunta1);
        this.listaPreguntas.add(pregunta2);
        this.listaPreguntas.add(pregunta3);
        this.listaPreguntas.add(pregunta4);
    }

    private void cargarPreguntas() {
        this.cbPregunta1.removeAllItems();
        this.cbPregunta2.removeAllItems();
        for (int i = 0; i < this.listaPreguntas.size(); i++) {
            this.cbPregunta1.addItem(this.listaPreguntas.get(i));
            this.cbPregunta2.addItem(this.listaPreguntas.get(i));
        }
        this.cbPregunta1.setSelectedItem(null);
        this.cbPregunta2.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbPregunta1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtRespuesta1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbPregunta2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JTextField();
        btnRecuperar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Recuperar contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione y responda las preguntas de seguridad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 310, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Pregunta 1:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, -1));

        cbPregunta1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPregunta1ActionPerformed(evt);
            }
        });
        jPanel1.add(cbPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 400, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Respuesta 1:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, -1));

        txtRespuesta1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta1ActionPerformed(evt);
            }
        });
        txtRespuesta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuesta1KeyTyped(evt);
            }
        });
        jPanel1.add(txtRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 400, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pregunta 2:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, -1));

        cbPregunta2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPregunta2ActionPerformed(evt);
            }
        });
        jPanel1.add(cbPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 400, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Respuesta 2:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, -1));

        txtRespuesta2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta2ActionPerformed(evt);
            }
        });
        txtRespuesta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRespuesta2KeyTyped(evt);
            }
        });
        jPanel1.add(txtRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 400, -1));

        btnRecuperar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 110, -1));

        btnCancelar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta1ActionPerformed

    private void cbPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPregunta1ActionPerformed

    }//GEN-LAST:event_cbPregunta1ActionPerformed

    private void txtRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta2ActionPerformed

    private void cbPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPregunta2ActionPerformed

    }//GEN-LAST:event_cbPregunta2ActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        int temp1 = this.cbPregunta1.getSelectedIndex();
        int temp2 = this.cbPregunta2.getSelectedIndex();
        if (temp1 == temp2) {
            JOptionPane.showMessageDialog(null, "Debe responder preguntas diferentes.");
        } else {
            if (this.usuario.respuestas.get(temp1).equals(this.txtRespuesta1.getText())
                    && this.usuario.respuestas.get(temp2).equals(this.txtRespuesta2.getText())) {
                FrmNuevaContraseña frmN = new FrmNuevaContraseña();
                frmN.setVisible(true);
                frmN.usuario = this.usuario;
                frmN.nombreUsuario(this.usuario.usuario);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Respuesta incorrecta.");
            }
        }
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtRespuesta1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtRespuesta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuesta1KeyTyped
        if (this.txtRespuesta1.getText().length() >= 35) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRespuesta1KeyTyped

    private void txtRespuesta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRespuesta2KeyTyped
        if (this.txtRespuesta1.getText().length() >= 35) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRespuesta2KeyTyped

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
        new FrmLogin().setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntasSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntasSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntasSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPreguntasSeguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPreguntasSeguridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JComboBox<String> cbPregunta1;
    private javax.swing.JComboBox<String> cbPregunta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    // End of variables declaration//GEN-END:variables
}
