/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import clases.Usuario;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmRecuperarC extends javax.swing.JFrame {

    /*
    Preguntas de seguridad:
    1. Primera mascota
    2. En que ciudad se conocieron tus padres
    3. Nombre de la primera escuela a la que asististe
    4. Nombre de tu primera mascota
     */
    private ArrayList<String> listaPreguntas;
    private final String pregunta1 = "¿Cuál es el nombre de tu primera mascota?";
    private final String pregunta2 = "¿Cuál es el nombre de la ciudad en la que naciste?";
    private final String pregunta3 = "¿Cuál es el nombre de la primera escuela a la que asististe?";
    private final String pregunta4 = "¿Cuál era el apodo de tun infancia?";
    public Usuario usuario;

    /**
     * Creates new form FrmRecuperarC
     */
    public FrmRecuperarC() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.generarArray();
        this.cargarPreguntas();
    }

    private void generarArray() {
        this.listaPreguntas = new ArrayList<>();
        this.listaPreguntas.add(pregunta1);
        this.listaPreguntas.add(pregunta2);
        this.listaPreguntas.add(pregunta3);
        this.listaPreguntas.add(pregunta4);
    }

    private void cargarPreguntas() {
        this.cbPregunta1.removeAllItems();
        this.cbPregunta2.removeAllItems();
        for (int i = 0; i < this.listaPreguntas.size(); i++) {
            this.cbPregunta1.addItem(this.listaPreguntas.get(i));
            this.cbPregunta2.addItem(this.listaPreguntas.get(i));
        }
        this.cbPregunta1.setSelectedItem(null);
        this.cbPregunta2.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbPregunta1 = new javax.swing.JComboBox<>();
        txtRespuesta1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRespuesta2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbPregunta2 = new javax.swing.JComboBox<>();
        btnRecuperar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Recuperar contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel2.setText("Seleccione y responda las preguntas de seguridad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 290, -1));

        cbPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPregunta1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 84, 350, -1));

        txtRespuesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtRespuesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 122, 350, -1));

        jLabel3.setText("Pregunta 1:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 89, 69, -1));

        jLabel4.setText("Respuesta 1:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 127, 70, -1));

        txtRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRespuesta2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtRespuesta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 215, 350, -1));

        jLabel5.setText("Respuesta 2:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 69, -1));

        jLabel6.setText("Pregunta 2:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 182, 69, -1));

        cbPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPregunta2ActionPerformed(evt);
            }
        });
        getContentPane().add(cbPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 177, 350, -1));

        btnRecuperar.setText("Recuperar");
        btnRecuperar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecuperar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRespuesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta1ActionPerformed

    private void cbPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPregunta1ActionPerformed

    }//GEN-LAST:event_cbPregunta1ActionPerformed

    private void txtRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRespuesta2ActionPerformed

    private void cbPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPregunta2ActionPerformed

    }//GEN-LAST:event_cbPregunta2ActionPerformed

    private void btnRecuperarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarActionPerformed
        int temp1 = this.cbPregunta1.getSelectedIndex();
        int temp2 = this.cbPregunta2.getSelectedIndex();
        if (temp1 == temp2) {
            JOptionPane.showMessageDialog(null, "Debe responder preguntas diferentes.");
        } else {
            if (this.usuario.respuestas.get(temp1).equals(this.txtRespuesta1.getText())
                    && this.usuario.respuestas.get(temp2).equals(this.txtRespuesta2.getText())) {
                FrmNuevaContra frmN = new FrmNuevaContra();
                frmN.setVisible(true);
                frmN.usuario = this.usuario;
                frmN.nombreUsuario(this.usuario.usuario);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Respuesta incorrecta.");
            }
        }
    }//GEN-LAST:event_btnRecuperarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.txtRespuesta1.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRecuperarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRecuperarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRecuperarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRecuperarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRecuperarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuperar;
    private javax.swing.JComboBox<String> cbPregunta1;
    private javax.swing.JComboBox<String> cbPregunta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtRespuesta1;
    private javax.swing.JTextField txtRespuesta2;
    // End of variables declaration//GEN-END:variables
}
